MNT_DIR="/mnt"
TMP_DIR="/temp"
OUT_DIR="/out"
SRC_DIR="/src"
UTILS_DIR="/utils"

NASM_BIN="/usr/bin/nasm"
LD_BIN="/usr/bin/ld"
OBJCOPY_BIN="/usr/bin/objcopy"
CHECKSUM_LOCAL_BIN="$UTILS_DIR/checksumpe"

BOOTX64_EFI_BUILD_MODE=0

# Build mode: 0
BOOTX64_EFI_SRC_FILE="$SRC_DIR/BOOTX64.asm"
BOOTX64_EFI_OUT_FILE="$OUT_DIR/EFI/BOOT/BOOTX64.EFI"

# Build mode: 1
BOOTX64_DBG_ELF_SRC_FILE="$SRC_DIR/BOOTX64_DBG.asm"
BOOTX64_DBG_O_TMP_FILE="$TMP_DIR/BOOTX64_DBG.o"
BOOTX64_DBG_ELF_TMP_FILE="$TMP_DIR/BOOTX64_DBG.ELF"
BOOTX64_DBG_LD_SCRIPT="$SRC_DIR/EFI_DBG.lds"
BOOTX64_DBG_FLAGS="-g -F dwarf"

ENABLE_CREATE_IMG_FILE=1
IMAGE_NAME="OS.img"
IMAGE_SIZE=1000  # In Kb
ENABLE_CREATE_ISO_FILE=0
