name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install NASM
      run: sudo apt-get update && sudo apt-get install -y nasm

    - name: Run build script
      run: ./build.sh  

    - name: Upload BOOTX64.EFI
      uses: actions/upload-artifact@v4
      with:
        name: BOOTX64.EFI  
        path: ./out/EFI/BOOT/BOOTX64.EFI
        
    - name: Upload OS.img
      uses: actions/upload-artifact@v4
      with:
        name: OS.img  
        path: ./OS.img
        
